---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

roles:
  - name: mambaorg.micromamba
    version: main
    src: https://github.com/mamba-org/ansible-micromamba

collections:
  - name: community.general
    version: ">=6.0.0"

  - name: ansible.posix
    version: ">=1.5.0"
